-- MomShop — seed catalog.
--
-- Intentionally empty: this is a general handmade boutique and the client will
-- add their own categories and products (hats, earrings, shirts, stickers, and
-- more) once the lineup + photography are ready. With no rows, the site shows
-- "Coming soon" states everywhere.
--
-- The schema in 0001_init.sql is a generic catalog (a grouping table +
-- products). NOTE: when wiring the DB, consider renaming `materials` ->
-- `categories` (and `products.material` -> `category`) to match the
-- general-boutique model, and drop the earrings-era `style` column if unused.
--
-- Example shape (uncomment + adapt when ready):
-- insert into public.materials (slug, name, tagline, description, image, sort_order)
--   values ('hats', 'Hats', 'Cozy + handmade', 'Hand-finished hats.', '/images/hats.jpg', 1);
-- insert into public.products (id, slug, name, material, style, price, images, short_description, description)
--   values ('example', 'example', 'Example', 'hats', 'Beanie', 28, ARRAY['/images/example.jpg'], 'Short blurb.', 'Longer description.');
